//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessagesByContact
    {
        public int MessageID { get; set; }
        public int ContactID { get; set; }
        public System.DateTime SendDate { get; set; }
        public int ID { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Message Message { get; set; }
    }
}
